### ISSUE TITLE
Duplicate tags!

### ISSUE THREAD

**Issue by burzum** [UseMuffin/Tags#24]
### Duplicate Tags

**It is possible to save two tags with the exact same label.**

See the test I've added here. https://github.com/burzum/Tags/tree/bug/duplicates

And it should not even possible to save "Tags" and "tags" at the same time IMHO.

In combination with sluggable this lead into a pretty terrible situation for our data import: It created a **new** tag for duplicates and then sluggable tried to generate a slug in a while loop - which becomes slower and slower over time because it has to test for a hell of existing slugs by incrementing the number: `tag-1, tag-2, tag-3,...`. This effectively slowed down the whole import to an unacceptable time and would slow down even a regular application over time.

The bug will over a longer time cause a massive slowdown when adding "new" tags! The more tags (duplicates!) you get the longer it will take.

Besides the slug there should be a "key" field in the tags table that keeps a lowercased or Inflector::slug()`ed version of the label so it can be used to check against duplicates even in case sensitive collations.

### Wrong tests & code

The plugin features namespaces, I think somebody screwed up the namespaces when writing the _normalizeTag() method and the test. It should not split "foo:bar" into id and label but in namespace and label!

```php
    protected function _normalizeTag($tag)
    {
        $id = null; // THIS IS WRONG! Should be "namespace"!
        $label = $tag;
        $separator = $this->config('separator');
        if (strpos($tag, $separator) !== false) {
            list($id, $label) = explode($separator, $tag);
        }

        return [
            trim($id),
            trim($label)
        ];
    }
```

Part of the test:

```php
    public function testNormalizeTags()
    {
        $result = $this->Behavior->normalizeTags('foo, 3:foobar, bar');
        $expected = [
            [
                'label' => 'foo',
                '_joinData' => [
                    'fk_table' => 'tags_muffins',
                ],
            ],
            [
                'id' => 3, // THIS IS WRONG! Should be "namespace"!
                '_joinData' => [
                    'fk_table' => 'tags_muffins',
                ],
            ],
            [
                'label' => 'bar',
                '_joinData' => [
                    'fk_table' => 'tags_muffins',
                ],
            ],
        ];
        $this->assertEquals($expected, $result);
  }
```

**Comment by davidyell** [comment]
Sounds logical to me. Worth adding an index to the slug fields too I'd imagine.
