### ISSUE TITLE
Field 'slug' doesn't have a default value 

### ISSUE THREAD

**Issue by aiphee** [UseMuffin/Tags#26]
Hi, is the plugin still working for cakePHP 3.1?
I am getting an error 
```
Field 'slug' doesn't have a default value 
```

**Comment by ADmad** [comment]
Either ensure a value is set for your slug field when creating new record or set DEFAULT NULL for your table field.

**Comment by virusvn** [comment]
"Field 'slug' doesn't have a default value" came from the table tags_tags of this plugin.
This plugin will not through an error if we install plugin https://github.com/UseMuffin/Slug, or make field "slug" to "DEFAULT NULL" on the table tags_tags.
