### ISSUE TITLE
Update to CakePHP 3.7.4, Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by vnt** [UseMuffin/Tags#39]
How can I resolve this problem?

Update to CakePHP 3.7.4 from 3.5.9
 composer update --with-dependecies

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - muffin/tags dev-master requires cakephp/migrations ^2.0 -> satisfiable by cakephp/migrations[2.0.0, 2.1.0].
    - muffin/tags dev-master requires cakephp/migrations ^2.0 -> satisfiable by cakephp/migrations[2.0.0, 2.1.0].

**Comment by ADmad** [comment]
Why are you using `dev-master` for the plugin? Use release.
