### ISSUE TITLE
Tests pass but tags are not saved in a real app

### ISSUE THREAD

**Issue by burzum** [UseMuffin/Tags#5]
Tests pass but tags are not saved in a real app.

* Behavior is loaded
* TagAwareTrait is used

But no tags get saved.

**Comment by ADmad** [comment]
As a [wise man said](https://twitter.com/jose_zap/status/586460893522845696) unit tests are not enough :)

**Comment by ADmad** [comment]
Problem was caused due to tables created by migrations file not using column names the behavior expects by default. I have updated the files. Check now.

**Comment by burzum** [comment]
Thanks!
