### ISSUE TITLE
Tags and migrations won't work with UUID type ids

### ISSUE THREAD

**Issue by burzum** [UseMuffin/Tags#6]
The migrations are made to work with integer type ids but not UUIDs.

I've faced this problem in the past, maybe we can find a solution (config?) to this with the migrations plugin.

By looking at the migrations they extend the AbstractMigration class, we could add a CakeMigration class that implements an initialize() method where settings from Configure could be read and used for something.

**Comment by ADmad** [comment]
This sounds like a limitation of Migrations plugin. Not an issue with Tags plugin itself. So would be better to open an issue on Migrations tracker.

**Comment by burzum** [comment]
Yes and no. We can work around that like I proposed inside the plugin itself until the migration plugin is is improved, if this ever passes.
